### ISSUE TITLE
Appify catalog

### ISSUE THREAD

**Issue by bldng** [interactivethings/catalog#110]
Use Electron to create a Catalog app. 😎 
The goal is to have an editor that can create and edit Catalog pages. In the end, a static site could be exported. When the app is opened, you can drop a Catalog folder to edit it. Continue to use Git to create versions and sync with others.

This would also remove most of the remaining initial setup challenges (like starting a server in terminal) related to the current standalone process.

**Comment by herrstucki** [comment]
This is somewhere on our wish list but needs a few steps taken first. Also the goal is not 100% clear right now and needs better definition.
