### ISSUE TITLE
Specimen Props Generator

### ISSUE THREAD

**Issue by bldng** [interactivethings/catalog#112]
Automatically compose samples for a specimen.

**Comment by bebraw** [comment]
See [react-docgen](https://github.com/reactjs/react-docgen). You can extract a JSON out of a component definition with all the props quite easily. This would be a great addition.

**Comment by herrstucki** [comment]
I'm closing this for now, as I don't see any immediate action. Feel free to re-open with more details.

**Comment by lucasmotta** [comment]
Hey @herrstucki, I've been playing around with Catalog for a new project I've been working on, and displaying the prop types documentation is a key part for this.

I've been looking into it and I found [this babel plugin](https://github.com/storybooks/babel-plugin-react-docgen) that embeds the documentation into the component. It would be neat if we could include it on the default `.babelrc` of catalog, then create a Specimen for displaying somewhere in your documentation. Something within the lines of:

```
```react-props
component: ButtonComponent
``` 
```

Would then generate something like this:

<img width="943" alt="screen shot 2018-01-23 at 12 45 07" src="https://user-images.githubusercontent.com/76673/35281971-77b4d83a-003b-11e8-81d8-57e96390a110.png">


What do you think? If you are keen with this implementation, I can look into creating the Specimen for this - also let me know if you think we should have options for it.
