### ISSUE TITLE
Table specimen

### ISSUE THREAD

**Issue by bldng** [interactivethings/catalog#115]
New specimen that allows to generate tables easily.

**Comment by herrstucki** [comment]
I'd see something like the [`console.table`](https://developer.mozilla.org/en-US/docs/Web/API/Console/table) API as useful and more usable than Markdown tables. E.g.

    ```table
    rows:
      - {id: 1, value: 'foo'}
      - {id: 2, value: 'bar'}
    ```

Additionally, an array of `columns` could restrict which columns are displayed.

**Comment by herrstucki** [comment]
🚢 ed in `v2.4.0`
