### ISSUE TITLE
Consolidate theme configuration

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#120]
Before we document the theme configuration options, I'd like to clean up unused and redundant options. Most notably:

- The `font[S-Xxl]` sizes shouldn't be used anywhere because we use a modular scale
- I'm not sure about the `size[S-Xxl]` values and their relation to `baseVerticalUnit`
- Make sure there's no font loaded from Google Fonts when another font is specified (move font import to theme config?)
- I'm not sure why `DefaultResponsiveSizes` is exported separately from DefaultTheme.js

**Comment by wereHamster** [comment]
`baseVerticalUnit` is not used anywhere. It was used in `setType(…)` / `text(…)` (src/scaffold/typography.js) but that file was removed in bf74351 (Style refactor, 2015-12-18).

**Comment by wereHamster** [comment]
Now font sizes are based off of `baseFontSize` and `msRatio`. But still, `fontX` are used in some places.

**Comment by herrstucki** [comment]
Yeah, it'd be great to replace those …
