### ISSUE TITLE
Alias jsx specimen to react specimen?

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#128]
I realized I can use Catalog to render [my project](https://github.com/bebraw/reactabular) readme by using the React specimen. The problem is that GitHub Markdown doesn't pick that up. jsx would work, though.

Do you think it would be possible to do an alias for this case? Then we could get something that would work for both GitHub and Catalog allowing these sort of things easily. Even better, provide an user space aliasing mechanism so you can avoid requests like this.

**Comment by herrstucki** [comment]
Yeah, good point. We should probably alias the GFM-style highlighted code blocks to our own, so this will just work:

    ```javascript
    const foo = 'bar';
    ```

The only thing I'm worried about is potential name clashes with Catalog Specimen types.

**Comment by bebraw** [comment]
I guess handling a couple of the most important ones would help. Or, as suggested, you could push the problem to the user space somehow.

**Comment by naehrstoff** [comment]
So there are basically two use-cases that would make it useful to be able to register custom specimens as discussed in #114:

* Easily add your own or community contributed specimens. This is currently possible if you're using React to build your pages, but not if you're using Markdown. I consider Markdown as an important part of Catalog's API and therefore think that it would be quite important to be able to do this.
* Be able to use standard code highlighter names and alias them to a specimen type. The question is whether these mappings will have to be slightly more elaborate, e.g. they might have to provide `javascript` as an argument to the `code` specimen.

To me both these use-cases make sense as they strengthen the use of Markdown.

**Comment by herrstucki** [comment]
FWIW, the mechanism to create custom specimens (also to use them in Markdown) already exists. It's just not documented because I haven't fleshed the public API fully out so far.

You can already map a `javascript` code block like this:

```js
import {CodeSpecimen} from 'catalog';
const catalogConfig = {
  title: 'Foo',
  specimens: {
    javascript: (props) => <CodeSpecimen {...props} lang='javascript' raw />
  },
  pages: [/*…*/]
}
// etc.
```

Currently Catalog warns if a specimen type is not available. We could also opt to fall back to use Code Specimens with `lang` set by default.

**Comment by bebraw** [comment]
@herrstucki Thanks. That worked perfectly.

Is there some particular reason Catalog can't be used through a normal import (`import Catalog from 'catalog'` btw? I had to set up

```javascript
      {
        test: require.resolve('catalog'),
        loader: 'expose?Catalog'
      }
```

kind of loader declaration on my project to make it work.

**Comment by herrstucki** [comment]
Catalog doesn't have a default export because it messes up UMD builds if you mix default and named exports. If you use Babel, import the named exports, e.g.

```js
import {render} from 'catalog';
```

**Comment by bebraw** [comment]
```javascript
import * as Catalog from 'catalog';
```

fixed it for me.

Thanks for the pointer. This might be good to mention at the docs.
