### ISSUE TITLE
Generate several specimens of the same code snippet but with different modifiers

### ISSUE THREAD

**Issue by naehrstoff** [interactivethings/catalog#13]
In order to efficiently test various modifiers of a component without duplicating code all the time, it would be nice to be able to specify a list of modifier classes and then generate all variations.

```
<a class="button">…</a>
<a class="button button--important">…</a>
<a class="button button--large">…</a>
<a class="button button--important button--large">…</a>
```

The last example shows that it might be interesting to specify a list of lists of modifiers.

Creating React components for this and passing in different properties could be a solution. Those components could then be `toString()`ed to output “real” HTML. Let's see.

**Comment by herrstucki** [comment]
Related to #39

**Comment by mhintz** [comment]
The React component specimen thing is pretty tricky. The route I tried goes as follows:

include browser babel somehow (or another in-browser JSX compiler)
Include the react component source files somehow
pass the component class definitions into Catalog via the `dependencies` object
Inside the specimen renderer, compile the JSX statement using babel
wrap the compiled code in a call to `new Function`, being sure to include `React` and the stringified names of the jsx dependencies as arguments to the function.
execute that function, passing the React instance object and all the jsx class objects.
render the return value of the function as a child of the rendered specimen

This approach broke down at the very last stage. When outside code defines React components, and then you try to render them inside Catalog, it's important that both Catalog and the outside components reference the same version of React. The way our module system works, its entirely possible for React's source code to be included twice, and to generate two separate objects. You can't render components derived from one React's `React.Component` using the other React's `React.render`. The render function doesn't recognize it as a valid component. So both Catalog, and the React components which are to be displayed by it, need to reference the same React instance variable in the browser.

These are things to keep in mind while developing a JSX Catalog specimen

**Comment by herrstucki** [comment]
I'm closing this for now, as I don't see any immediate action. Feel free to re-open with more details.
