### ISSUE TITLE
Support custom tips/warnings at Markdown

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#138]
Sometimes you may want to use special emphasis for tips/warnings. I've settled for `T>` and `W>` for these purposes. Basically I style these cases differently. Here's my [implementation](https://github.com/survivejs/site/blob/master/utils/markdown.js) you could consider plugging in.

It actually would be enough for me if you could expose marked enough so that I can do these kind of hacks in the user space. You might not want all of this in the core.

**Comment by herrstucki** [comment]
For that we have the [Hint Specimen](https://interactivethings.github.io/catalog/#/specimens/hint) 🙂
