### ISSUE TITLE
Allow linting code examples

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#139]
It would be handy if there was some kind of interface for getting to the code examples so you can run a linter against them. This way you can ensure the examples follow your standards more easily.

**Comment by naehrstoff** [comment]
Is this problem solvable with the technique outlined in comment https://github.com/interactivethings/catalog/issues/126#issuecomment-228665768 ?

Alternatively you could create a custom specimen that does the linting. But of course that depends on the ideas in https://github.com/interactivethings/catalog/issues/128

**Comment by bebraw** [comment]
@naehrstoff That #126 comment covers it well. If I can inject my own preprocessor, I can definitely lint there.

**Comment by naehrstoff** [comment]
Great, then I'll close this issue for now.
