### ISSUE TITLE
Allow styling of the navigation sidebar per path

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#140]
Currently my navigation sidebar looks like this:

![screenshot 2016-06-30 18 42 21](https://cloud.githubusercontent.com/assets/166921/16494575/7ed62b20-3ef2-11e6-94bd-e6816b43fe08.png)

Given there are so many items, it's starting to hurt the UX. It would be good if there was some way to attach custom styling to the items. If you had `props` field or similar per path entry, that would work for me. Then I could set `borderBottom: '2px solid #ddd'` and end up with this:

![screenshot 2016-06-30 18 45 12](https://cloud.githubusercontent.com/assets/166921/16494702/f50ab1d0-3ef2-11e6-90fe-212e3ed48d57.png)

That would give a sense of hierarchy.

**Comment by wereHamster** [comment]
To add hierarchy, you can nest pages. See https://interactivethings.github.io/catalog/#/configuration -> Page Groups.

Note that currently only a single level of nesting is supported (I believe limited by how the sidebar is styled in CSS).

**Comment by bebraw** [comment]
There's actually some hierarchy in place already (Table, Formatters etc. expand), but that's a fair point.

Good to know about the limited nesting. Now that I think of it, if it supported two levels, I could perhaps collapse Table...Search below an entity of its own. Essentially those borders work around this issue as they provide some hierarchy.

**Comment by herrstucki** [comment]
@bebraw We're aware of this problem, we ran into this in one of our own projects with a large documentation 😅 . I don't think three (or infinite) levels of hierarchy are a good solution (at least visually). I like the idea of structuring the top level though.

**Comment by bebraw** [comment]
@herrstucki Yeah. Infinite nesting would just push the problem elsewhere. I would be totally happy with path based customization as then I can do my own thing easily. 👍

**Comment by herrstucki** [comment]
I'm closing this issue for now, as it's part of a larger holistic redesign effort which we want to undertake but haven't planned at the moment.
