### ISSUE TITLE
Allow linking to specific parts of documentation from navigation

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#151]
In my [current documentation](http://reactabular.js.org/) I have a bunch of code examples inlined with the conceptual parts. It would be useful if it was possible to add links to the navigation so that they link to these inlined examples. In terms of configuration I mean something like this:

``` javascript
{
  path: 'examples/table-header-example',
  title: 'Table Header Example',
  link: 'table/header#example'
},
```

So instead of generating an entire page, it would generate a link to another, ideally with an anchor.

**Comment by herrstucki** [comment]
This will finally soon be released in v2.5. You can test it in `catalog@next`. Please let me know if you encounter any bugs!
