### ISSUE TITLE
Renders "none" before and after quotes

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#155]
You can see the bug in action [here](https://survivejs.github.io/react-component-boilerplate). The quote has "none" before and after.

If I'm understanding right, that's because of [typography](https://github.com/interactivethings/catalog/blob/273520b724218b994eb6ee367da519e9651d057b/src/styles/typography.js#L145) sets it to "none" and the behavior could have gotten broken in [radium](https://www.npmjs.com/package/radium) `0.17.2`.

Maybe you could fix this by using `''` instead of `'none'`? If you can confirm the issue, we probably want to push it upstream as well.

**Comment by herrstucki** [comment]
Thanks for reporting! Seems like https://github.com/FormidableLabs/radium/pull/719 is the culprit.

I wonder if that rule is even needed …

**Comment by bebraw** [comment]
Thanks. I reported it upstream, https://github.com/FormidableLabs/radium/issues/780 .

If you can simplify the styling and get rid of the declaration, I guess that would be the best.

**Comment by bebraw** [comment]
It was made high priority so I guess we'll see a fix rather sooner than later. 👍

**Comment by herrstucki** [comment]
Ah thanks :smile:! In this case we could use `quotes: 'none'` anyway; the pseudo-element approach is for ancient browsers.
