### ISSUE TITLE
Implement tabbed variant of code/example display?

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#162]
It could be handy if you could customize code/example display somehow. A tabbed variant like [this](https://docs.sencha.com/extjs/6.0.1-modern/Ext.tab.Panel.html) could look neat.

It would be enough if there was an extension point that would accept the current specimen data. That would allow the users to implement something like this unless you want to provide this yourself.

**Comment by herrstucki** [comment]
Thanks for the suggestion. We'll keep it in mind for the next design iteration.

**Comment by ziyafenn** [comment]
Hi there!
Wanted to check if there is update on that.

In my case, we use 2 different frameworks and we wanted to merge them into one Design Library.

So would be nice to have tabs to switch between codes for different frameworks or design files.
Thanks.
