### ISSUE TITLE
Documentation sidebar fails to scroll at Safari 9

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#166]
1. Open Safari 9 (I'm on OS X myself)
2. Open https://interactivethings.github.io/catalog/#/specimens
3. Scroll the main area.
4. Move cursor to the sidebar and scroll.
5. Note how it still scrolls the main area.

I cannot reproduce this in Chrome so I guess it's something Safari specific.

**Comment by herrstucki** [comment]
Seems like a Safari bug to me. I can reproduce it in stable Safari but not in the (latest) Safari Technology Preview. So I don't think there's much we can do, unless someone has an idea.
