### ISSUE TITLE
Provide better traces for `SyntaxError`

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#171]
It would be nice to get a trace if a specimen fails. Hard to say anything concrete without. Maybe restrict only to development mode (node env set to "develop").

Related to #170.

**Comment by herrstucki** [comment]
I'm not really sure to which level we should handle user/compilation errors. Syntax errors in React Specimens should be displayed properly on the page already.

I'm closing this for now, as I don't see any immediate action. Feel free to re-open with more details.
