### ISSUE TITLE
Achieve IE9 compatibility

### ISSUE THREAD

**Issue by naehrstoff** [interactivethings/catalog#191]
Catalog is also useful for enterprisey projects that still need to support older browsers. We should try to support IE9 at least. It currently complains about missing `requestAnimationFrame` support.

**Comment by herrstucki** [comment]
We're only using https://github.com/chrisdickinson/raf/ which should fall back to `setTimeout`. Are you sure that it's an issue of Catalog?

**Comment by herrstucki** [comment]
IE 11 should work now, I don't think we can support IE9/10 because we use of Flexbox. I'm gonna close this. If you feel like giving this a shot anyway, please open a PR 😁
