### ISSUE TITLE
Weird behavior with componentDidMount and ref offsetHeight

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#195]
For some reason `offsetHeight` seems to yield zero at initial `componentDidMount` if I enter a component page directly. If I visit some other page and get back to the page, it gives expected non-zero results.

Here's how to repro if you are interested:

1. Clone https://github.com/reactabular/reactabular/tree/virtualized-glitch .
2. `npm run init`
3. `npm start`
4. Surf to `http://localhost:8080/#/virtualization`. Note the console output. Visit another route and go back. Note the console output again. You can repeat the behavior by forcing a hard refresh on `http://localhost:8080/#/virtualization`.

To give you a better idea of output, consider the screenshots below. I tested this on Chrome 52.

**Initial `componentDidMount`**

![screenshot 2016-08-29 14 59 38](https://cloud.githubusercontent.com/assets/166921/18050968/692f4144-6dfa-11e6-9d07-969bb7d98205.png)

**`componentDidMount` after visiting another route**

![screenshot 2016-08-29 14 58 56](https://cloud.githubusercontent.com/assets/166921/18050970/6bc39e3c-6dfa-11e6-834d-7036a2c5878e.png)

Any ideas on why this might happen would be welcome. That `componentDidMount` behavior feels just strange. Maybe it could have something to do with the way the playground is initialized the first time?

**Comment by bebraw** [comment]
I found a workaround. If you set `frame: true`, the initial height calculation works. That's enough for now although it would be better to fix the underlying issue.

**Comment by bebraw** [comment]
Is there anything I can do to help with this? Iframes come with problems of their own (broken styling).

**Comment by wereHamster** [comment]
Could it be because Radium injects the styles with a short delay (setTimeout or requestAnimationFrame), and therefore DOM measurements are not accurate when done directly in `componentDidMount`? Did you try to measure the offset in a `setTimeout` started from `componentDidMount`?

**Comment by bebraw** [comment]
That's worth trying. Thanks for the tip! I'll give it a go and report back tomorrow,

**Comment by bebraw** [comment]
@wereHamster That's it, yeah. The problem is that I would have to adjust my component code to bend this to work with Radium. I also don't know when Radium completes. Something like `setTimeout(() => this.forceUpdate(), 100)` at `componentDidMount` works, but applying an arbitrary delay like that doesn't feel clean.

I wonder what's the right fix for this. I guess I'll hit this with Radium users outside of Catalog. 😖

**Comment by herrstucki** [comment]
It's a common problem with CSS-in-JS solutions which inject styles asynchronously (Aphrodite suffers from the same behavior). https://github.com/airbnb/react-with-styles looks like an interesting approach, especially the ability to flush styles before the component gets rendered. Not sure if that's possible with Radium …

**Comment by bebraw** [comment]
I solved this on my side. I had to do a bit of trickery to detect whether or not the height has changed but in the end it's better this way.

I guess you could mark this closed after documenting the gotcha.

**Comment by herrstucki** [comment]
Great! Do you think there's something specific to Catalog we should document? Elements not having the correct dimensions on `componentDidMount` seems like a pretty common pattern to me in practice.

**Comment by bebraw** [comment]
Maybe add a little tip at the [React specimen](https://interactivethings.github.io/catalog/#/specimens/react) doc. It won't have to be much. Something along what you said would help I think.
