### ISSUE TITLE
Importing modules to ReactSpecimen 

### ISSUE THREAD

**Issue by ajainvivek** [interactivethings/catalog#253]
Hi,

Importing modules returns undefined

Import statement
`import * as MDL from 'react-mdl';`

Hooked to pages
```
{
    path: '/demo',
    title: 'Demo',
    imports: {
      Dummy,
      MDL
    },
    component: demo
  }
```

React Specimen

```
<ReactSpecimen span={10}>
      {`
        <div>
          <Dummy library={MDL} /> // Reference passed returns undefined -> expectation is to pass modules
        </div>
      `}
</ReactSpecimen>
```

Thanks,

**Comment by herrstucki** [comment]
Are both `Dummy` and `MDL` defined values at the point where you import them (i.e. in the pages configuration)? Do you get an error message in Catalog itself?

**Comment by ajainvivek** [comment]
I don't get any error message from Catalog while importing but returns undefined in ReactSpecimen while consuming.

**Comment by herrstucki** [comment]
Did you include the MDL Javascript [like it's instructed here](https://github.com/react-mdl/react-mdl#create-react-app)? What does Catalog show? Are there any console error messages?

If this problem persists, please provide a reproducible example, preferably as a Gist or in its own Repo. In the meanwhile, I'm going to close this issue.
