### ISSUE TITLE
Integration with React app

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#26]
Catalog should be usable in an existing React app to document components

**Comment by mhintz** [comment]
I think this requires moving React to `peerDependencies`

**Comment by herrstucki** [comment]
I don't think so … what we need to do if we expose it as a npm library is to make a custom library build with webpack (because we use loaders and babel). There we can specify React as an external dependency, so it won't be included in the library build.

See http://webpack.github.io/docs/configuration.html#externals

**Comment by mhintz** [comment]
ohhh, ok. So then webpack would leave the `React = require('react')` calls in there, and expect that whatever consumer uses the bundle can provide the dependency

**Comment by herrstucki** [comment]
Yep, at least that's how I think that'll work.

**Comment by herrstucki** [comment]
:ship:ed in 2.0.0-alpha7
