### ISSUE TITLE
Is `path` a required option on all levels now?

### ISSUE THREAD

**Issue by naehrstoff** [interactivethings/catalog#265]
I just tried to upgrade from Catalog `2.4.0` to `2.5.0.beta7` and got an error because I did not define `path` on every level of the config. I had something like this (taken from Catalog's current online documentation):

    Catalog.render({
      title: 'My Catalog',
      // NOTE: No `path` field on this level
      pages: [
        {
          path: '/',             // The path where the page can be accessed
          title: 'Introduction', // The page title
          src: 'docs/intro.md'   // Path to the Markdown document
        },
        // Other pages …
      ]
    }, document.getElementById('catalog'));

If I add a `path` field to the top level (i.e. right after `title: 'My Catalog'`) it works. I got the hint that I need to do this from Catalog's own config on its website.

My questions now are the following:

1. Was this breakage introduced accidentally?
2. If it was introduced consciously: what is the reason for it (because the path you have to specify there will never actually be seen)
3. If it was a conscious decision: do we really want this?

**Comment by herrstucki** [comment]
Seems like a bug to me … not sure why that would be useful otherwise.
