### ISSUE TITLE
Table of Contents?

### ISSUE THREAD

**Issue by StephenOTT** [interactivethings/catalog#268]
Anyone work on a Table of Contents that follows the user down the page? (following the Headings).

This is typically useful for longer pages with lots of headings.

**Comment by herrstucki** [comment]
No, no one's working on this at the moment. This probably should be part of the main menu, and make sure this works on mobile too.

**Comment by herrstucki** [comment]
I'm closing this issue for now, as it's part of a larger holistic redesign effort which we want to undertake but haven't planned at the moment.

**Comment by StephenOTT** [comment]
THanks @herrstucki for the feedback

**Comment by herrstucki** [comment]
@StephenOTT no problem. If you have specific ideas or examples, feel free to add them here. I can't promise anything but it definitely helps to know what people want 😃
