### ISSUE TITLE
3.0.0.rc1 doesn't work with interactivethings brand guidelines catalog

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#289]
https://brand.interactivethings.com/

The second page has only `title` and `pages`, but no `path` (it's a page group). But the code in catalog requires that either `path` or `name` is always set (see https://github.com/interactivethings/catalog/blob/741d45f2a64720658ed7457b9f93d5643bcb8e67/src/configure.js#L83). If neither is set then the function `parsePath` throws an exception (https://github.com/interactivethings/catalog/blob/741d45f2a64720658ed7457b9f93d5643bcb8e67/src/utils/path.js#L11).

Options:

 1. This is a bug in the brand guidelines catalog configuration and `path` must always be set.
 2. This is a bug in catalog, and page groups are not required to have a `path`.

**Comment by herrstucki** [comment]
But `parsePath` won't be called when `page.pages` is defined?

**Comment by wereHamster** [comment]
Ok, works now. I was using the wrong version of catalog. It can be confusing not seeing which exact version of catalog is being used.
