### ISSUE TITLE
flex-basis displaying %NaN when fenced blocks don't include span helper

### ISSUE THREAD

**Issue by sebastiangraz** [interactivethings/catalog#293]
basically 

```
```html|
 <a href="javascript:;" class="pv3 ph4 br-pill bg-c-blue white bw1 link dim dib">Call to action</a>```
```
Doing this and not suppling the `|span-X` gives the CSS a %NaN in the flexBasis calc property 

<img width="322" alt="screen shot 2017-06-05 at 17 23 15" src="https://cloud.githubusercontent.com/assets/25587798/26792869/b8553d64-4a13-11e7-8abb-406a5b50c5e6.png">

A quick fix for this was to add

```
if (span == undefined) {
  span = 6
}
```
inside the `Span.prototype.render = function render()` block 

Any thoughts? Is the fix doable for now?

**Comment by bldng** [comment]
Thanks for reporting!
It is resolved in the latest version, the default value was never applied.
