### ISSUE TITLE
Code preview extends beyond it's boundaries when expanded. 

### ISSUE THREAD

**Issue by sebastiangraz** [interactivethings/catalog#294]
![kapture 2017-06-05 at 17 35 03](https://cloud.githubusercontent.com/assets/25587798/26793309/6806c5ec-4a15-11e7-8925-65dadd38fe96.gif)

Pasted a Gif from the Catalog website to showcase the problem. This problem is especially prominent when using `|span-X` and the code is very likely to be longer than the html content itself

Appreciate any help on this issue!

**Comment by herrstucki** [comment]
@sebastiangraz this is fixed in v3, will be released soon! If you use Catalog from npm, you can try `catalog@^3.0.0-rc.3` or the standalone browser version from https://unpkg.com/catalog@3.0.0-rc.3/dist/catalog-standalone.min.js.

**Comment by umbriel** [comment]
@herrstucki Hey, thanks for providing the release candidate! Do you have a unminified version at hand perhaps? Because I've done some minor hacking the get the previous version to work and I don't want to redo everything again.
