### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#295]
```
Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at formatProp
    at …
    at Array.map (native)
    at reactElementToString
```

One can not `JSON.stringify(…)` a React element, and indeed the `formatProp` function contains a check, but only on the first level of props. If the React element is contained deeply inside the props object (eg. `<MyComponent prop={{foo: { bar: { baz: <div /> } } }} />` then `formatProp` tries to use `JSON.stringify` still.

I also discovered a potential optimisation: the code to render the react element to string is hit even though I set`noSource: true`. The `ReactSpecimen.prototype.render` function calls `reactElementToString` regardless of the `noSource` value.

**Comment by herrstucki** [comment]
I didn't really fix it but at least we now show an error message instead of failing completely: 02ab696
