### ISSUE TITLE
Allow overriding (or turn off) font family for ReactSpecimen component

### ISSUE THREAD

**Issue by vjwilson** [interactivethings/catalog#298]
We're using Catalog to build a styleguide of our React components.

We're creating <component>.doc.jsx docs to use for the _component_ properties in the pages array, and one each of those pages, we are using 1 or more <ReactSpecimen> components to wrap our components.

ex.
```
        <ReactSpecimen span={6}>
          <SelectInput
            dataList={dataList}
            handleSelection={this.handleSelection}
            selectedItem={this.state.selectedItem}
            promptText="Choose a filter"
            extraClass="some-class"
          />
        </ReactSpecimen>
```

but the React specimen component is overriding the font-family with Roboto in an inline style. We didn't notice it at first, because our body font is also Roboto, but when we came to headings, it's overriding our component's CSS. (We are not using any kind of inline style or CSS-in-JS for this app, but relying on the cascade for things like font-family.)

Could we make at least the font-related inline styles in ReactSpecimen where they could be turned off?

**Comment by wereHamster** [comment]
Try the `frame` option, it will completely isolate your component from the catalog (render it in an iframe).

**Comment by vjwilson** [comment]
I did try the `frame` attribute, but it didn't inject our custom CSS into the iframe, so our React component just had default browser styling.

It looks like the inline style for the font is set at [src/specimens/Type.js, line 22](https://github.com/interactivethings/catalog/blob/8d6d3e634f512d382a29c2708f4f152a822e9e7b/src/specimens/Type.js#L22). I'm not familar with the Catalog codebase, but would it be possible for me to add an optional boolean prop to ReactSpecimen which, if true, would just change that style setting to `fontFamily: inherit`?

I'd be glad to submit a PR, if someone would point me in the right direction.

**Comment by herrstucki** [comment]
@vjwilson which version of Catalog are you using? Have you tried `3.0.0-rc.3`? We did fix this in 96753979a2cd71815ccd0c748c0bebcfdcd4c9a3.

BTW, you _can_ inject your own CSS into the framed mode when [`styles` are set](https://interactivethings.github.io/catalog/#/configuration?a=styles) on your page config. Or are you using a different styling method (CSS-in-JS)?

**Comment by vjwilson** [comment]
@herrstucki ,

We are using 2.5.3. We'll give 3.0.0-rc.3 a try.

We are not setting styles in React at all. We set classNames, because the client already has a style system with different themes, already written with good, old-fashioned CSS.

**Comment by vjwilson** [comment]
@herrstucki , @wereHamster 
Finally got around to upgrading our project to 3.0.0-rc.3, and it seems to fix this font issue.
Closing this issue.
