### ISSUE TITLE
Radium warning: do not mix longhand and shorthand properties in the same style

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#300]
(catalog v3.0.0-rc.3)

Just received a warning from Radium: 

> Radium: property "border" in style object […]: do not mix longhand and shorthand properties in the same style object. Check the render method of Page. See https://github.com/FormidableLabs/radium/issues/95 for more information.

The object in question contains `border: "solid transparent"` as well as `borderTopColor: "#d80070"` and `borderWidth: "12.0px"`.

**Comment by herrstucki** [comment]
That looks odd. Doesn't seem to be a style from Catalog itself 🤔

**Comment by herrstucki** [comment]
Probably an issue where Radium is attaching itself to a specimen that's not framed. Nothing we can do at the moment I think.
