### ISSUE TITLE
formatProp() throws exception if a prop is explicitly set to `undefined`

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#301]
```javascript
export default () => (
  <Page>
    <ReactSpecimen span={1} noSource>
      <Rating
        rating={2}
        dimKey={undefined}
      />
    </ReactSpecimen>
  </Page>
)
```

The issue is in the following code:

https://github.com/interactivethings/catalog/blob/c113b1a60cae9033cf7b1f35f3534429c58121f9/src/specimens/ReactSpecimen/reactElementToString.js#L43-L53

`JSON.stringify(undefined)` returns undefined, and so the code continues to access `v.name` -> 💣

**Comment by wereHamster** [comment]
One workaround is to set `sourceText` to a non-empty string, especially useful in conjunction with `noSource`. Example:

```javascript
<ReactSpecimen noSource sourceText={'.'}>
    <Rating dimKey={undefined} />
</ReactSpecimen>
```

**Comment by kaityhallman** [comment]
this issue is still occurring.
