### ISSUE TITLE
Does v3.0 support images out of box without CRA?

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#303]
I saw there's some image loader code for CRA. Should images work without it too? If not, can I extend webpack configuration somewhere. That's a little bit unclear at the moment. Other than that, Catalog 3 is looking good.

Related: https://github.com/reactabular/reactabular/issues/323

**Comment by herrstucki** [comment]
Yes, Catalog uses a CRA-like webpack config also when CRA is not present.

BUT images referenced in Markdown files don't get compiled by webpack (it's on my list but it's a bit tricky). Only the ones that you import in your JS files. Images in `<catalog-dir>/static` are treated like CRA's `public/` directory, so you should be able reference them anywhere.

**Comment by bebraw** [comment]
Ah... Thanks for the tip. I'll try `/static` then. I had a relative lookup in place.

**Comment by bebraw** [comment]
About processing images in Markdown, I solved it like [this](https://github.com/survivejs-sites/template/blob/master/loaders/page-loader.js). Let me know if you need more info. I just rewrite the images to webpack `require` and that's it.

**Comment by bebraw** [comment]
It probably would be good if you could expose webpack configuration somehow so that I can extend it. I would have to set a `DefinePlugin` and maybe some `resolve` rules. Do you want a separate issue for this?

**Comment by herrstucki** [comment]
Yes, parsing the markdown and replacing the image references is what's necessary to do it. Thanks for the example!

I'm not sure if I want to support extending the existing webpack config. To me that sounds like a hacky way of doing things (because you have to rely on rule ordering and also know the shape of the incoming config where I can't guarantee that it'll be stable). For now, I suggest to use a custom webpack setup (skipping the Catalog CLI entirely) instead.

**Comment by herrstucki** [comment]
_But_ if webpack supported a way to safely compose different configurations, I'd be happy to support it. I don't want to build a custom mechanism for that though ;)

**Comment by bebraw** [comment]
> I'm not sure if I want to support extending the existing webpack config. To me that sounds like a hacky way of doing things (because you have to rely on rule ordering and also know the shape of the incoming config where I can't guarantee that it'll be stable). For now, I suggest to use a custom webpack setup (skipping the Catalog CLI entirely) instead.

Ok. I agree it's a can of worms. It would be perfect for my use case as the base configuration does 99%. It's only a thing or two I need to add. I guess I'll skip customization for now to keep this simple.

The way I would do this is like:

**webpack.config.js**

```javascript
module.exports = (env, config) => { // pass your config as second parameter
  // env === 'catalog.build' or 'catalog.dev' for example

  ...  // now I do my stuff

  return modify(config); // modify as needed 
};
```

This is very close to webpack's configuration mechanism. I only added that `config` parameter. The rest is same. So you would have to detect for the file, pass env and config, capture output, and then use that. This hook would be enough for me and easy to document too.

**Comment by herrstucki** [comment]
I opened a separate issue for the config problem: #304

I assume the image problem is solved, so I'm closing this issue.

**Comment by bebraw** [comment]
> I assume the image problem is solved, so I'm closing this issue.

Yeah, solved apart from the Markdown bit. Maybe you could open an issue to track that so I can do updates on my end later. You need two bits to solve it: 1. rewrite image links at your Markdown parser 2. rewrite those rewrites as `require`.
