### ISSUE TITLE
CLI: add support for catalog.config.js?

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#304]
It _might_ be useful to support a config file for the CLI to use as an alternative to command line arguments and configure more advanced stuff like the webpack config. I'm undecided if this is really a good idea, since modifying webpack configs is error-prone.

As an alternative to just passing in Catalog's webpack config we could expose hooks to add (remove? replace?) more loaders and plugins more safely. If only webpack provided a bit more help with this, for example allowing to assign IDs to rules/plugins, so subsequent consumers of the config could reference them properly instead of relying on a config's particular shape.

And ideally, there would be a package which already did the dance of figuring out the final configuration from CLI args, config file (and env vars?) …

Also see:
- https://github.com/interactivethings/catalog/issues/303#issuecomment-334152371
- https://github.com/zeit/next.js/#customizing-webpack-config

**Comment by bebraw** [comment]
FYI, [webpack-merge](https://www.npmjs.com/package/webpack-merge) is pretty handy for the use case but that's more of a user level concern. As long as there's a hook, you can compose however you like.

Even a limited hook (black box) would be a start.

**Comment by jneuendorf** [comment]
I just tried to figure out where exactly to put the config file: It must be in the directory from where the start command is run (I believe ^^). Maybe this should be stated in the docs.
