### ISSUE TITLE
Support for vue.js

### ISSUE THREAD

**Issue by berteltorp** [interactivethings/catalog#308]
Neat project - support for [vue.js](https://vuejs.org/) would be much appreciated! 🙏

**Comment by herrstucki** [comment]
Sure, why not? 😊

However, I‘m not familiar with Vue and would need some guidance on how that should work. How would you want to include Vue components as a user? It seems there‘s tons of ways how to write them (templates, JS template literals, JSX, …). Can you render them outside of a Vue app?

**Comment by herrstucki** [comment]
Maybe https://github.com/akxcv/vuera could be useful for this.

**Comment by herrstucki** [comment]
Closing in favor of #423
