### ISSUE TITLE
Rendering router-related components

### ISSUE THREAD

**Issue by oyeanuj** [interactivethings/catalog#311]
Hi folks! I wasn't able to find any guidance in the docs around how to incorporate components that use React-Router's `Link` component under `ReactSpecimen`. Just inserting them as regular children gives the following error:
```
Warning: Failed context type: The context `router.history` is marked as required in `Link`, but its value is `undefined`.
    in Link (created by Menu)
    in li (created by Menu)
    in ul (created by Menu)
    in Menu
```

My guess is that we have to use the `MemoryRouter` in some way - is there a recommended way?

Thank you!

**Comment by wereHamster** [comment]
Yes, that's what you have to do, wrap your component in whatever context provider it requires. Same if the component requires apollo for example.

**Comment by oyeanuj** [comment]
@wereHamster Cool, thanks! I'll try that. Maybe this should go to the Guide/README as well?
