### ISSUE TITLE
Install Overwrites webpack-dev-server .bin symlink

### ISSUE THREAD

**Issue by larkintuckerllc** [interactivethings/catalog#315]
Took me some time to figure out what was going on.  The original symptom is that after installing catalog, starting webpack-dev-server spun up two instances (8000 and 8001).  Discovered that the install of catalog was overwriting the symbolic link in .bin

This seems problematic as I just lost control of which version of webpack-dev-server I am running.

webpack-dev-server -> ../catalog/node_modules/webpack-dev-server/bin/webpack-dev-server.js

**Comment by herrstucki** [comment]
That sounds like a npm/yarn issue. I‘d assume that when you specify the webpack-dev-server version that you want in your package.json, that’s the version that gets linked.

Anyway, I can’t really do anything here unless you  provide more information about your specific setup. Ideally a reproducible case in a repo/gist.

**Comment by larkintuckerllc** [comment]
After a bit more investigation, it looks like there was a discrepancy between the version of webpack-dev-server that I was using (older) than the one that you were using (newer).  Apparently Yarn will install the newer version under the catalog folder (and happensto update the global .bin - weird).  My fix was simply to update my version to match catalog's.  BUT... Part of the problem that I see is that you have a single repository for both the standalone and the React embedded solutions (thus you have a lot of unneeded dependencies if you are going the React embedded solution).

**Comment by herrstucki** [comment]
Yes, that’s a great point. Splitting catalog into separate packages has been on my mind for some time but didn’t make the cut for the current release. Thanks for reporting this 🙏!
