### ISSUE TITLE
Catalog Build Directory

### ISSUE THREAD

**Issue by mattfelten** [interactivethings/catalog#317]
It looks like there's not a way to build to a directory. I'm running `catalog build` but I have no idea what/where it's building to.

I guess a further question, I'm trying to build out a static site for documentation that I'll rsync up to a server. I was thinking that was what `catalog build` was for, but maybe I'm wrong. Is there a way to do this with Catalog?

**Comment by herrstucki** [comment]
By default, `catalog build` will build to `catalog/build` but you can change that with the `--out`/`-o` option, e.g.

```
catalog build -o my-build-dir
```
