### ISSUE TITLE
Pages Hidden From Navigation

### ISSUE THREAD

**Issue by mattfelten** [interactivethings/catalog#318]
I'd like to make a page full of my react components to use to test variations and such but I don't want it to show up in the sidebar. Is there a way to have a page with a route but hidden from navigation?

**Comment by mattfelten** [comment]
Answered my own question! Looks like there's a `hideFromMenu` prop for pages.
https://github.com/interactivethings/catalog/blob/aa19e78d6f1a2b02efa0bd8fdc1e29492a622e9e/src/components/Menu/Menu.js#L93

Wonder if this should be documented?

**Comment by herrstucki** [comment]
I would accept a PR at https://github.com/interactivethings/catalog-docs/ 😉

**Comment by mattfelten** [comment]
When you're right, you're right! Added at interactivethings/catalog-docs#6
