### ISSUE TITLE
Module not found: Error: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by oyeanuj** [interactivethings/catalog#324]
Hi folks! I installed `catalog` via the CLI and running into the following issues when I try `catalog build` or `catalog start`:

```sh
Module not found: Error: Can't resolve 'child_process' in 
./internal/utils.js, 
./node_modules/happypack/lib/HappyThread.js, 
./node_modules/node-notifier/lib/utils.js
```

So far, after installing, I've added `catalog/babel` to my .babelrc and Markdown loaders as specified in the guide. Any ideas on what might be going on? 

FWIW, I'm on Node 8 and my regular builds seem to be working fine without any such error.

Thank you!

**Comment by herrstucki** [comment]
Hi! 

From the trace it looks like an issue outside of Catalog (it uses neither of those modules). My best guess is maybe a dependency conflict.

If you can share a setup that I can run, I can try to investigate but otherwise it’s hard to tell what’s going on.
