### ISSUE TITLE
Consider adding postcss-import

### ISSUE THREAD

**Issue by disintegrator** [interactivethings/catalog#327]
Hey thanks for the amazing project!

I am currently building a doc site for my company's design system and trying to figure out how to load up our styles package which is published on our internal npm registry.

The steps I tried:

- yarn add company-styles
- `echo '@import "company-styles"' > catalog/static/styles.css`
- in catalog/index.js:
```
ReactDOM.render(
  <Catalog
    theme={theme}
    styles={['/styles.css']}
    title="Company style guide"
    pages={pages}
  />,
  document.getElementById('catalog'),
);
```

Now this is not working probably due to Catalog not configuring postcss in the webpack config to use [postcss-import](https://github.com/postcss/postcss-import).

Is there currently a way to solve this problem or shall I submit a PR to add postcss-import?

**Comment by herrstucki** [comment]
You can modify Catalog‘s default webpack config using `catalog.config.js` https://docs.catalog.style/guides/webpack-babel

I‘m not sure but maybe using a `postcss.config.js` file could also work.

**Comment by disintegrator** [comment]
Thanks for the tip @herrstucki! I'll give it a go and report back shortly

**Comment by disintegrator** [comment]
@herrstucki despite many attempts, I was unable to get `@import` in css files located under `static/` to be inlined at build time. I wanted to avoid overwriting catalog's default webpack config so I did not create my own `catalog.config.js`. I tried using `postcss-import` with `postcss.config.js` at the root of my project but that was not being picked up during build/dev.

If I understand things correctly, resources under `static/` are not processed by webpack.
I also tried placing my css file at `catalog/styles.css` and then specifying `styles={['./styles.css']}` but that didn't work either.
The only things that works now is to have a `catalog/styles.css` contain:
```
import "~company-styles"
```
The tilde indicates it's a node module.
and then importing the file (`import './styles.css'`) at the top of `catalog/index.js`
While nothing is broken right now, I fear the css in the package will conflict with catalog's styling...

If this is a case of user error then I'm happy to close the issue. Otherwise, if you have some follow-up advice I'd be happy to continue investigating.

Thanks again for all the help!

**Comment by disintegrator** [comment]
After some reflection, I've come to the conclusion that it is a bad idea to open up this capability in Catalog. I now run my asset building and Catalog server in parallel. With this workflow, Catalog will rerender docs with the updated css on every rebuild. Closing...
