### ISSUE TITLE
[Theming] Navigation bar background and menu icon

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#338]
Hi, the navigation bar background and the mobile menu icon are not themeable:

![screen shot 2017-11-23 at 09 38 23](https://user-images.githubusercontent.com/10454741/33164211-1da90296-d032-11e7-92ae-6770766edff5.png)

If i set a lighter heading background i should be able to change the icon color
![screen shot 2017-11-23 at 09 39 43](https://user-images.githubusercontent.com/10454741/33164244-33fbd398-d032-11e7-8706-709bcf3d2cca.png)

**Comment by equinusocio** [comment]
No responses yet?

**Comment by equinusocio** [comment]
@bldng Thank you!  When this fix will be released?

**Comment by herrstucki** [comment]
@equinusocio Released in v3.2.0 ✌️

**Comment by equinusocio** [comment]
Top!

**Comment by equinusocio** [comment]
So we now have `navBarBackground` and `navBarTextColor`?

**Comment by equinusocio** [comment]
@herrstucki On github there is not the latest release (3.2.0 on NPM)

**Comment by herrstucki** [comment]
Yeah, the hover state seems to be broken … @bldng?

**Comment by equinusocio** [comment]
News?

**Comment by herrstucki** [comment]
@bldng?

**Comment by bldng** [comment]
The opacity was set too high (0.9) – it's updated in master and will ship with the next release.

**Comment by herrstucki** [comment]
@equinusocio @bldng 🚢 as v3.2.1
