### ISSUE TITLE
[Question] Web components

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#339]
Hi, is there a way to use catalog with web components? or polymer elements?

**Comment by herrstucki** [comment]
Using the [HTML Specimen](https://docs.catalog.style/specimens/html) should work as expected if the custom element is registered.

Ping @bldng

**Comment by equinusocio** [comment]
@herrstucki Will this work only with vanilla web components right?

**Comment by herrstucki** [comment]
I‘m afraid I don’t know what vanilla web components are. Have you tried to use web components in the HTML Specimen? Any components loaded on the page should work.

**Comment by equinusocio** [comment]
Im able to use web components with the html specimen by importing it.
