### ISSUE TITLE
Idea: Storybook specimens

### ISSUE THREAD

**Issue by disintegrator** [interactivethings/catalog#342]
I've been wondering lately if Catalog is able to leverage stories written for storybook as part of writing documentation. Storybook has a rich ecosystem of addons and integrations (https://github.com/oblador/loki) that can improve test and development workflows greatly.

Proposed usage:

<pre><code>
```storybook
kind: Forms
story: Validations
```
</code></pre>

It will be important for the Storybook specimen to be able to pull the code for a story and render it alongside the demo as with the React specimen today.

**Comment by herrstucki** [comment]
Cool idea! I'm not familiar with Storybooks' implementation though. I imagine re-purposing `storiesOf()` could be tricky. Do you have an idea _how_ to do this?

**Comment by herrstucki** [comment]
Also, I don't think this should be part of Catalog's core but would make a nice add-on (probably integrating with the CLI). If anyone's interested in building this, I'd be glad to assist by adding the necessary API to Catalog itself.

**Comment by disintegrator** [comment]
Glad to hear you like the idea. I was definitely not suggesting you build it haha. I'll see if I can set aside some time over the holiday to come up with something.
If you do have some more thoughts on how something like this should be built. I think it would be nice if Catalog supported external specimens.
e.g. `Catalog.registerSpecimen('storybook', StorybookSpecimen)`

**Comment by herrstucki** [comment]
Cool!

It's already possible to add custom Specimens. It's just not documented yet 😅 

The simplest form of it is this:

```jsx
<Catalog specimens={{storybook: StoryBookSpecimen}} />
```

The YAML/JSON config from the specimen inside the Markdown maps directly to a Specimen's props.

There's a [Specimen higher-order component](https://github.com/interactivethings/catalog/blob/master/src/components/Specimen/Specimen.js)  to provide layout and theme info to custom Specimens. You may not need to use that to prototype something.

What's not really possible yet is to hook into the Catalog CLI's build system. If you need to do that, let me know what would be useful to add there.

**Comment by disintegrator** [comment]
Oh wow that's awesome! It'll make thing easier for sure :)

**Comment by herrstucki** [comment]
Closing in favor of #423
