### ISSUE TITLE
spawn catalog.js-start ENOENT

### ISSUE THREAD

**Issue by szare** [interactivethings/catalog#343]
I'm using catalog inside a boilerplate, after ```npm start```, I'm receiving the following error:
spawn catalog.js-start ENOENT

Node: 8.9.1
Npm: 5.5.1
OS: Windows 10

**Comment by herrstucki** [comment]
Which Catalog version are you using?

**Comment by bebraw** [comment]
@herrstucki It's the newest. [Here](https://github.com/survivejs/react-component-boilerplate). See also https://github.com/survivejs/react-component-boilerplate/issues/41 .

**Comment by herrstucki** [comment]
Looks like it's related to this issue 👉  https://github.com/leo/args/issues/88 … which was already fixed? 🤔 

Can you check with `npm ls args` which version is installed?

**Comment by herrstucki** [comment]
Ah yes, seems like you have 3.0.4 locked. If you upgrade that, it should work.

https://github.com/survivejs/react-component-boilerplate/blob/a6c4bfbfea682e86b8d2b4013347c5757130e5ac/package-lock.json#L336

**Comment by bebraw** [comment]
Ok, thanks. I'll upgrade.

**Comment by herrstucki** [comment]
I'll also bump the dependency version for Catalog

**Comment by herrstucki** [comment]
Released in v3.2.2

**Comment by szare** [comment]
@herrstucki @bebraw Thank you so much. It fixed.
