### ISSUE TITLE
Spacing specimen

### ISSUE THREAD

**Issue by kyleoliveiro** [interactivethings/catalog#346]
Any plans to support a specimen for spacing values? We use spacing values for things like `margin`, `padding`, `grid-gap`, `column-gap` etc.

For an illustrated example: "sizes" section on https://scarab-styleguide.surge.sh/#/theme

**Comment by herrstucki** [comment]
No immediate plans, but if you want to add it, feel free to create a custom Specimen. See https://github.com/interactivethings/catalog/issues/342#issuecomment-350840275

Happy to help with any issues!

**Comment by kyleoliveiro** [comment]
I've started work on this. Input on what props the Specimen should support is welcome!

@herrstuck I have a question about the `theme` constant in your Specimen files. For example in `src/speciments/ColorPalette.js`,  there are references to `theme` but it is never defined in the file. When I try to use the `theme` constant in my own Specimen file, I get `ReferenceError: theme is not defined`.

**Comment by kyleoliveiro** [comment]
For anyone else looking to create a custom Specimen, here are the steps I've taken. Since there's no formal documentation on the matter, maybe this will be helpful to someone.

- Create your custom Specimen in the `src/specimens` folder.
- It may be helpful to refer to the other Specimen components in the `src/specimens` for guidance on how to author your custom Specimen.
- Import your newly created Specimen in `src/speciments.js`, `src/index.js` and `src/index-standalone.js`.

**Comment by mattfelten** [comment]
I'm interested in using this. As long as the quantity of spacing steps are configurable, what is shown in your example will work for me. We're currently using 16 sizes which is a pretty fair amount of spacing sizes.

**Comment by kyleoliveiro** [comment]
I've submitted a [pull request](https://github.com/interactivethings/catalog/pull/349) that adds this feature.

**Comment by herrstucki** [comment]
Closing in favor of #423
