### ISSUE TITLE
How to configure public url?

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#348]
Hi, i have an issue publishing the build folder content under a gh-page.

My gh-page is set to serve all files from the root of the `master` branch. My gh-page url is:

`https://contactlab.github.io/repo-name/`

I have an issue with the static js files because they have a path starting with `/static/...` and i need to make them start with `/repo-name/static` since using `/static` return 404. Setting the `basePath` does not change the generated paths. Any suggestion?

**Comment by herrstucki** [comment]
`catalog build --public-url=/repo-name/` should do the trick. Note that the files in `catalog/static` will end up at `/repo-name/`, _not_ `/repo-name/static/`

**Comment by equinusocio** [comment]
@herrstucki Thank you. The catalog now just run fine, but as you said, static content files now return 404. There is a way to fix this?

**Comment by herrstucki** [comment]
For example: `catalog/static/foo.jpg` should be referenced like `/foo.jpg` in your Markdown documents, then it should work.

**Comment by equinusocio** [comment]
mmm i'm just importing some static md files as pages with the `pageLoader()`

```
pageLoader("/pages/design_system/INTRODUCTION.md")
```

But inside the source files the `/pages` is inside the static folder. When builded, it get moved at the root (as you said)

**Comment by equinusocio** [comment]
@herrstucki Just fixed by removing the `/` at the begin -> `pageLoader("pages/design_system/INTRODUCTION.md")`

**Comment by herrstucki** [comment]
Ok, cool. Sorry for the confusion. I'll have to check if that can be improved or documented better.

**Comment by equinusocio** [comment]
@herrstucki Can i ask just another question? Is there a way to change the build (folder) path?

**Comment by mdotasia** [comment]
@herrstucki Setting `--public-url` in the build command works, but it is not intuitive. I first followed the docs and added `basePath` and `useBrowserHistory` to my config. `basePath` should be ignored when running `catalog-start` and only used for `catalog-build`. Either way, it would be helpful if the docs mentioned this.
