### ISSUE TITLE
Multiple sources for audio/video specimens

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#359]
Hi since audio and video objects allows more sources for fallbacks is useful if we can set multiple sources fot these specimens.

**Comment by equinusocio** [comment]
Hi, any update? do they works like images with multiple src?

**Comment by herrstucki** [comment]
No update at the moment, sorry. I'll let you know when someone has time to work on this. Do you have a more concrete proposal on how this would work?

**Comment by equinusocio** [comment]
Since the video element accept more source types, it can just accept a src format like the image speciment. Something like this:

```
src: "/assets/my-video.mp4 video/mp4, /assets/my-video.webm video/webm"
```
