### ISSUE TITLE
Where to place images/ assets

### ISSUE THREAD

**Issue by plaetzchen79** [interactivethings/catalog#360]
First of all, Thank you for catalog!

I am just trying to display images (logSrc and in content-files ) but can't figure out why catalog/ the browser does not display them.

I have created an additional assets-folder and just placed the image in the main dir.

But after running npm catalog-start he cant find/ display the images.

It seems like that they are not in the "build"-folder.
I have tried to copy them there but no success.

Example:
  <Catalog title='StyleGuide' basePath='/' logoSrc='/assets/splash.png'

```image
dark: true
span: 4
src: "/assets/splash.png"
```

What i am missing?

**Comment by herrstucki** [comment]
By default, assets from `catalog/static/` can be referenced. For example: `/static/foo.jpg` -> `logoSrc="/foo.jpg"`

**Comment by plaetzchen79** [comment]
Thank you. Its working  :-)

**Comment by mergin** [comment]
I had to create a "public" folder in the root folder in order to show images with npm run catalog-start

I'm I doing something wrong or is there something wrong with de docs?

```image
light: true
span: 3
src: "brandmark_hero.png"
```
```
├── catalog/
├── public/
│   └── brandmark_hero.png
└── node_modules/
```
