### ISSUE TITLE
Trouble with standalone version

### ISSUE THREAD

**Issue by sheepshaver13** [interactivethings/catalog#364]
Hi,
I'm just trying to set up a styleguide for my NGO and getting into some traps.
We want to use catalog standalone and set up the styleguide in a github repo into master branch.

1) Embedding standalone-dev leads to a blank page and the following error:
`TypeError: objectAssign$1 is not a function. (In 'objectAssign$1(pureComponentPrototype, ReactComponent.prototype)', 'objectAssign$1' is undefined)`
on line 7823
Using standalone.min.js everything is fine.

2) Markdown-pages ignore where they are:
If I try to embed a logo in index.html with loroSrc a relative path is working:
`logoSrc: "catalog/assets/logo.png"`
Trying the same thing into a markdown document lying into _repo/catalog/_ e.g. using the image-specimen leads to an error, because catalog searches at
_org.github.io/_ and not at _org.github.io/repo_
So I have to name the full path
`image
src: "repo/catalog/assets/logo.gif"
`
what is just driving me crazy.

I guess there are some easy solutions, but actually I feel like beeing a blockhead.
Thomas

**Comment by herrstucki** [comment]
Hi!

1. seems to be a polyfill issue. I'll have to check the build of the standalone version.
2. If you're using hash-based routes (e.g. ones starting with `#/`), you should also be able to reference assets relative to the `index.html`. E.g. `logoSrc: "logo.png"` (if logo.png and index.html are in the same directory). If you're using routes without hashes (by setting `useBrowserHistory: true`), https://docs.catalog.style/configuration/other#basepath is what you're looking for.

**Comment by sheepshaver13** [comment]
Thanks for fixing the development version!
I built it by myself - seems like unpkg isn't updated yet.

I'm using hash-based routes and relative paths are working in index.html, but not in markdown files. I checked up the implementation of the catalog docs (v 2.5) to look how your solution works. But this won't work for me too.
Are there any problems regarding GitHub when using catalog-standalone?

**Comment by sheepshaver13** [comment]
I may concretise:
My error occurs only in Markdown-files.
E.g. in my logo.md:
```
image
src: "/catalog/assets/logo.gif"
title: "Logo"
```
is a reference to 
org.github.io/catalog/assets/logo.gif
instead of
org.github.io/**repo-name**/catalog/assets/logo.gif

Outside of Markdown-pages or rather specimens everything works fine.

**Comment by herrstucki** [comment]
How about `src: "catalog/assets/logo.gif"` (without the leading slash)?

**Comment by sheepshaver13** [comment]
...was one of my tries and doesn't change anything :-(

**Comment by herrstucki** [comment]
@sheepshaver13 I just released v3.3.0 which contains the standalone fix.

Files referenced in Markdown files need to be in `catalog/static/`. E.g. `catalog/static/foo.jpg` -> `src: "foo.jpg"`.
