### ISSUE TITLE
Whitespace issue with markdown tagged template literals

### ISSUE THREAD

**Issue by amytych** [interactivethings/catalog#366]
It seems that tagged template literals are whitespace sensitive when trying to set up React specimen with a state.

Everything works, if the definition starts from the beginning of the line

```
import { markdown } from "catalog"

export default () => markdown`
  > Button

~~~react
state: {clicked: 0}
---
<Button onClick={() => setState({clicked: state.clicked + 1})}>
  Clicked {state.clicked} times
</Button>
~~~
`
```

but if I try to indent it to align it with `> Button` above, like so:

```
import { markdown } from "catalog"

export default () => markdown`
  > Button

  ~~~react
  state: {clicked: 0}
  ---
  <Button onClick={() => setState({clicked: state.clicked + 1})}>
    Clicked {state.clicked} times
  </Button>
  ~~~
`
```

then the following error is thrown:

```
Couldn’t render specimen: SyntaxError: unknown: Invalid left-hand side in prefix operation (2:4)
1 | state: {clicked: 0}

    2 | —
    | ^
    3 | <Button onClick={() => setState({clicked: state.clicked + 1})}>
    4 | Clicked {state.clicked} times
    5 | </Button>
```

I've set up a [simple repository that showcases this problem](https://github.com/amytych/catalog-white-space-issue). This behavior is problematic especially when `prettier` is used, as it reformats the file with the indent.

**Comment by herrstucki** [comment]
That’s because Markdown _is_ whitespace-sensitive. Indented lines are treated as code blocks.

**Comment by amytych** [comment]
Thank you for the quick reply. Yes, that's correct.

I guess what got me confused is that only declarations with the state are whitespace sensitive in this case, any component without state might be indented without problems if enclosed in fenced code block `~~~`, so this works for example:

```
import { markdown } from "catalog"

export default () => markdown`
  > Button

  ~~~react
  <Button>
    Click me
  </Button>
  ~~~
`
```

I guess declaring the `state` property is the culprit here but I'm not sure if that's part of markdown or catalog specific implementation.

In any case, thanks again for the quick reply.

**Comment by herrstucki** [comment]
Yes, indeed … the issue doesn't seem Markdown-related. My guess is that the parsing of the specimen options separated by `---` don't account for the extra whitespace. If you'd like to give it a shot, I'd be happy to accept a fix! A good place to start would be to add a test case to https://github.com/interactivethings/catalog/blob/master/src/utils/parseSpecimenBody.test.js
