### ISSUE TITLE
srcset for image speciment

### ISSUE THREAD

**Issue by equinusocio** [interactivethings/catalog#370]
It would be useful having a way to set srcset for the image speciment

**Comment by herrstucki** [comment]
That's already possible: https://docs.catalog.style/specimens/image

**Comment by equinusocio** [comment]
Where? I can't find something similar to the srcset behavior..

**Comment by equinusocio** [comment]
The doc say that `src` is a string. What's the format?

`image.png 1x, image@2x.png 2x`?

**Comment by herrstucki** [comment]
You can use srcset notation (the regular one, e.g. `foo.jpg 1x,bar.jpg 2x`) on `src` and `overlay`.

**Comment by equinusocio** [comment]
Whats the default?

**Comment by herrstucki** [comment]
Yes.

**Comment by equinusocio** [comment]
@herrstucki Thank you again.
