### ISSUE TITLE
Scripts not importing

### ISSUE THREAD

**Issue by saoirse-zee** [interactivethings/catalog#372]
I'm trying to import some simple JavaScript to use in my specimens. I *think* I'm following the docs, but can't seem to get it working. Here's what I've got:

```
// index.js
const pages = [
  {
    path: "/",
    title: "Welcome",
    content: pageLoader(() => import("./WELCOME.md"))
  },
  {
    path: "/button",
    title: "Button",
    content: pageLoader(() => import("./button.md"))
  },
];

const pageGroup = [{
  title: 'My pages',
  scripts: ['./boo.js'],
  pages,
}]

ReactDOM.render(
  <Catalog
    title="Catalog"
    pages={pageGroup}
  />,
  document.getElementById("catalog")
);

// boo.js
function boo() {
  console.log('boo');
}

// button.md
```html
---
<div class="button" onclick="boo()">
  Boo
</div>
```
```

**Comment by herrstucki** [comment]
Is `boo.js` loading properly? You need to put it in `catalog/static/` and change scripts to `scripts: ['boo.js']` (the `./` part is necessary).

**Comment by saoirse-zee** [comment]
@herrstucki Thank you, this was helpful. I still could not make it work at the pageGroup level, which is what I was going for. Probably due to some mistake on my part. But I did get it working by putting the `scripts` at the page level:

```
{
      path: "/button",
      title: "Button",
      scripts: ['mockEventHandler.js'],
      content: pageLoader(() => import("./button.md"))
}
```

**Comment by herrstucki** [comment]
Yes, only individual pages and the top-level configuration support `scripts` (putting them on the top level makes them available on all pages). Sorry, I missed that detail from your original message!

I'm closing this now, since there's nothing actually wrong 😉
