### ISSUE TITLE
Script tags are not executed when specimen frame prop is set to true.

### ISSUE THREAD

**Issue by plumpNation** [interactivethings/catalog#373]
The html specimen componentDidMount() looks for script tags in the specimen markup. If it finds them, it will eval them.

However, if the html specimen property `frame` is `true`, then the lookup for script tags cannot find them, since the specimen markup is now in a different `window`.

**Comment by herrstucki** [comment]
Hi! This is the same issue as https://github.com/interactivethings/catalog/issues/340, therefore I'm closing this one.

**Comment by plumpNation** [comment]
OK I'll look at that. Thanks!
