### ISSUE TITLE
NPM install issue: Command not found: create-catalog

### ISSUE THREAD

**Issue by dlewand691** [interactivethings/catalog#374]
Getting the error `zsh: command not found: create-catalog` when trying to create a new Catalog with npm. 

Did these steps:
1. `npm install -g create-catalog`
2. `create-catalog /Users/ctsuser1/Desktop/catalog-test`

Node version is 9.4.0
NPM version is 5.6.0
MacOS 10.13.3

Everything worked fine using Yarn instead, thought you should know.

**Comment by herrstucki** [comment]
Hi @dlewand691, that's most certainly a problem with your particular Node setup. `create-catalog` usually is linked to `/usr/local/bin/create-catalog` with a global npm install.
