### ISSUE TITLE
Consolidate styling approach

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#38]
Strongly leaning to CSS modules in conjunction with Postcss-JS

**Comment by mhintz** [comment]
I think that, regardless of which styling approach we use, the structure of the styling code needs to be improved. At the moment, figuring out which styles are applied to any given object requires a whole lot of searching through auxiliary mixin/function definition files.

**Comment by herrstucki** [comment]
Sticking with Radium for now although it has some issues.
