### ISSUE TITLE
ReactSpecimen issue when built and minified

### ISSUE THREAD

**Issue by taddei** [interactivethings/catalog#384]
We're using `ReactSpecimen` to show how to use our components, as follow:

```jsx
    <ReactSpecimen showSource span={3}>
      <Button onClick={() => {}}>Click me</Button>
    </ReactSpecimen>
```

When running `catalog-build`, since it's going through the prod build and uglifyJS, the code gets built as:

```jsx
    <t showSource span={3}>
      <l onClick={() => {}}>Click me</l>
    </t>
```

And this is reflected in the output on the browser (see attached)

<img width="376" alt="screen shot 2018-03-05 at 13 28 53" src="https://user-images.githubusercontent.com/7198449/36977487-38aa155c-2079-11e8-8e76-91f871c97fb0.png">

**Comment by oliverjam** [comment]
It looks like Catalog uses whatever `.babelrc` is already in the project, so adding `"catalog/babel"` to our Babel presets fixes this 👍
