### ISSUE TITLE
Specimen: Button

### ISSUE THREAD

**Issue by dlewand691** [interactivethings/catalog#387]
Would recommend a generic "button" specimen. 

Can get used to download files, open internal links, open external links, etc. 

Styling can be taken from default CSS or custom CSS.

**Comment by equinusocio** [comment]
To download things you have the `download` specimen. To open external links you should use default links, not buttons. Then you can make your own react component and then use it with the `react` specimen.

**Comment by herrstucki** [comment]
Closing in favor of #423
