### ISSUE TITLE
Specimen request: Notification

### ISSUE THREAD

**Issue by dlewand691** [interactivethings/catalog#390]
Would like to request a new specimen type: **Notification**.

This would be used to create special alert type blocks that call out special notes about either do's, don'ts, cautions, or other items that need attention. 

Some examples in the wild are here:

[Shopify Polaris](https://polaris.shopify.com/visuals/colors): the "Do's" and "Dont's" sections. This site all together is pretty freakin' amazing anyway.

[Stylemark Bootstrap](http://stylemark-bootstrap.surge.sh/#button): See the big yellow boxes with alert icons. 

I would recommend/request:

- **Icon:** select what icon you want for the notification. Could be an asset located in the Static folder
- **Type:** This would allow for various types of notifications. Types could include warning (red), alert (yellow), plain (gray), positive (green)
- **Span:** same controls as other specimens
- **Design:** Could provide various styles: 
    - **Filled:** with full color and border of the same color darkened by X% (like the Stylemark example). 
    - **Border only:** filled with a light gray but colored border defined by type
    - **Header:** Band of color with icon and title, with body in gray. Similar to the Polaris example
    - **Vertical:** Thick border on the left side with icon vertically aligned inside. Body with gray background.

Happy to design comps for visual reference if agree this specimen is worthy.

**Comment by herrstucki** [comment]
We already have them: https://docs.catalog.style/specimens/hint

**Comment by dlewand691** [comment]
Oh my lord. Sorry, stupid mistake.
