### ISSUE TITLE
pageLoader doesn't work when mounting a Catalog directly from inside a Create React App ... app.

### ISSUE THREAD

**Issue by theinterned** [interactivethings/catalog#399]
Hello,

I have a project created with CRA. I want to be able to load a Catalog instance at a sub-route of that project. 

Here is a branch that demonstrates my issue:
 https://github.com/nulogy/design-system/tree/load-catalog-in-cra

I have a router (using redux router) that loads the Catalog: 

```js
const Routes = () => (
  <Router>
    <div>
      <Route exact path="/" component={App} />
      <Route exact path="/catalog" component={Catalog} />
    </div>
  </Router>
);
```
https://github.com/nulogy/design-system/blob/load-catalog-in-cra/src/Routes.js#L14

I run the project using the CRA command: `yarn start`

Everything loads well, however the markdown files are rendering into the pages as file paths to the `static` directory: rather then being parsed into page content, they show up in the content area as something like `/static/media/README.56de1b75.md`

For example, I have this config for the root page of the Catalog: 

```js
const pages = [
  {
    path: "/",
    title: "Welcome",
    content: pageLoader(() => import("./README.md"))
  },
// ...
];
```
https://github.com/nulogy/design-system/blob/load-catalog-in-cra/src/catalog/index.js#L6

When the page renders I am seeing this:

<img width="685" alt="screen shot 2018-04-10 at 7 37 41 pm" src="https://user-images.githubusercontent.com/2694/38589014-b36b26a2-3cf6-11e8-8914-293942bc7e82.png">

It looks to me like the CRA Webpack config is picking up the `.md` file and serving it from the static folder, and the `pageLoader` is getting the static file path when it is expecting the file content.

Do you have any suggestions for a work around? 

I thought it might be possible to load and parse the markdown from the Webpack static folder. But I wouldn't know where to begin on doing that.

Thanks!

**Comment by herrstucki** [comment]
Yes, that's a limitation of CRA. The Catalog command line tool uses a webpack loader to let you `import()` Markdown files – CRA doesn't support configuring webpack unless you eject.

Besides ejecting you have two options:

1. Use `pageLoader('WELCOME.md')` to load the file via a regular call to `fetch()` in the browser. For this to work, you need to move the file to `catalog/static/WELCOME.md`.
2. Turn your documentation files into `.js` files. This has a few other advantages, see https://docs.catalog.style/guides/react

More information on using Catalog's Babel preset and webpack loader: https://docs.catalog.style/guides/webpack-babel

**Comment by theinterned** [comment]
Thank you so much for the tips. Defining the pages as React components does indeed work! And I can certainly see the power it gives me.

However, My target audience for authoring docs in Catalog is designers with limited comfort with JS / React. I vastly prefer the pure Markdown flavour for this reason.

Looks like our requirements have changed and I won't need to define pages outside of Catalog anymore.
