### ISSUE TITLE
How to integrate Catalog into an existing CRA app?

### ISSUE THREAD

**Issue by theinterned** [interactivethings/catalog#400]
I would like to render a homepage / landing page at the root, and then load the catalog UI only in a sub-route (`/catalog`).

I have a few ideas but I'm not sure how to proceed:

1. Manually render the Catalog in my app. I have tried to do this, but I am running into Markdown parsing issues: https://github.com/interactivethings/catalog/issues/399
2. Somehow define a "Skinless page" as suggested in this issue: https://github.com/interactivethings/catalog/issues/331
3. Run `create-catalog` inside my CRA'd app. I'm have a number of problems with this approach however: https://github.com/nulogy/design-system/tree/catalog-style-cra
    1. I have to run 2 different dev serves; one for CRA with `yarn start` that runs on `localhost:3000`, and one for Catalog with `yarn catalog-start` that runs on `localhost:4000`. This makes it difficult to route between the two apps.
    2. I have to run 2 different build commands that build into to 2 different directories: CRA's `yarn build` outputs to the `/build` directory, while Catalog's `yarn catalog-build` outputs into the `/catalog/build` directory.

Do you have any tips about the best way to proceed?

Thanks

**Comment by electronspin** [comment]
I'm trying to get an instance of Catalog running inside a Gatsby site, and so I have similar questions. I'll share anything I figure out. If anyone has had luck getting Catalog running in Gatsby, please share!

**Comment by langermank** [comment]
> I'm trying to get an instance of Catalog running inside a Gatsby site, and so I have similar questions. I'll share anything I figure out. If anyone has had luck getting Catalog running in Gatsby, please share!

Did you end up using this in a gatsby site?

**Comment by theinterned** [comment]
Closing this stale issue
