### ISSUE TITLE
Deep linking appears to be broken when building with a --public-url and useBrowserHistory: true,

### ISSUE THREAD

**Issue by theinterned** [interactivethings/catalog#405]
Hello, 

I have the following project: https://github.com/nulogy/design-system

I am deploying my project to Github pages using the [`/docs` in `master` branch strategy](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch).

In order to achieve this I specify the `--out` and `--public-url` in my build script in package json:

```json
"scripts": {
    "start": "catalog start",
    "build": "catalog build --out docs/ --public-url /design-system"
  },
```

I also have `useBrowserHistory: true` specified in my catalog config.

Now when I run in dev mode using `yarn start` everything is fine. I can visit either http://localhost:4000/ or a sub-page http://localhost:4000/foundation/principles for example with no problem. I can hit refresh on either of these pages and everything works.

When I build and deploy however the deep links are broken. I can visit https://nulogy.github.io/design-system/ just fine, but if I deep link to (or refresh on) https://nulogy.github.io/design-system/foundation/principles I get a 404:

![screen shot 2018-04-17 at 9 18 30 pm](https://user-images.githubusercontent.com/2694/38906478-ee16a4f0-4284-11e8-9da5-c691a0fcf04b.png)

It seems like there may be a misconfiguration in React Router?

**Comment by theinterned** [comment]
Okay, I realize the problem with deep linking is a GH pages limitation. 

I’m going to give this a shot https://github.com/rafrex/spa-github-pages/blob/gh-pages/README.md

Or accept that I’m going to have to used the `hashHistory` and live with the ugly urls.

**Comment by herrstucki** [comment]
Yes, unfortunately GH Pages doesn't support this. We switched from GH pages to [Netlify](https://www.netlify.com/) a while ago for this reason (amongst others). You can also host on [now](https://zeit.co/docs/examples/create-react-app), [Surge](http://surge.sh/), or any other web server that [you can configure](http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/).

**Comment by theinterned** [comment]
Thanks for the tip @herrstucki are you open to a PR top update the docs with info about this?

**Comment by theinterned** [comment]
Nice!
