### ISSUE TITLE
Setting `PUBLIC_URL` env var has no same effect as `--public-url`

### ISSUE THREAD

**Issue by safareli** [interactivethings/catalog#409]
`catalog build --public-url=/styleguide` works fine, but `PUBLIC_URL=/styleguide catalog build` doesn't, is it a bug or what i'm doing wrong

**Comment by herrstucki** [comment]
Yes, you have to use a command line argument. If you need to read from an env var that is set somewhere else, `catalog build --public-url=$PUBLIC_URL` should do the trick.
