### ISSUE TITLE
Clean up dist and built files

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#41]
The built files shouldn't be committed to the master branch

**Comment by mhintz** [comment]
I agree wholeheartedly with this, but it's worth also noting that the built files should still probably be included in the gh-pages branch. And there are currently-deployed Catalogs out there which have a script tag pointing to the file at interactivethings.github.io

**Comment by naehrstoff** [comment]
Agreed, deploying built files to master is a no-go, please remove. Deploying built files to `gh-pages`, however, is being used and useful.Am 27.10.2015 um 11:35 schrieb Jeremy Stucki <notifications@github.com>:The built files shouldn't be committed to the master branch—Reply to this email directly or view it on GitHub.

**Comment by herrstucki** [comment]
The current solution is that the v1.x builds are still in the repo because we serve them from gh-pages. We should evaluate though if that's necessary. I _think_ we could remove them since I suspect were the only ones using Catalog until now and updating our projects wouldn't be too much effort.

v2.x builds are exclusively published to npm and currently served via https://npmcdn.com – which works great but it's still an early project as far as I can tell. So we need to keep an eye out.

I'm not entirely happy with the current publishing strategy but let's discuss this at a later point.
