### ISSUE TITLE
Failing nsp checks

### ISSUE THREAD

**Issue by rob1256** [interactivethings/catalog#418]
The current version of catalog is failing nsp vulnerability checks:

![screen shot 2018-05-14 at 08 45 50](https://user-images.githubusercontent.com/5627633/39984480-3fb4a630-5753-11e8-898f-5fcb98517676.png)

Fix for this is to upgrade the `url-loader` dependency to it's latest version of `v1.0.1` - As it's a major version upgrade though I'm not sure what could break as a result.

**Comment by herrstucki** [comment]
I don't think this is really an issue since `url-loader` is only used during development and at build time and therefore doesn't receive untrusted user input.
