### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#43]

**Comment by mhintz** [comment]
The module needs to be better npm-ified before this can happen, and we need to do a UMD-style export of the Catalog global. Also worth noting that at the moment, Catalog.start is the only entry point to the library. Whereas in the future, we want to be able to include Catalog components in any other React app (multiple entry points), and have Catalog.start be essentially a wrapper function which constructs a styleguide using those components. (Catalog "eats its own dogfood", so to speak)

**Comment by herrstucki** [comment]
In progress at #50
