### ISSUE TITLE
Any plan to upgrade to webpack 4?

### ISSUE THREAD

**Issue by brunoqueiros** [interactivethings/catalog#434]
Hi, do you have any plan to upgrade to webpack 4? Because I'm extending the catalog webpack config and I can't upgrade to webpack 4 because of it.

**Comment by wereHamster** [comment]
How are you extending the catalog webpack config? And which config? Because catalog doesn't provide a webpack config for end-users.

**Comment by brunoqueiros** [comment]
https://github.com/Vandebron/styleguide/blob/master/catalog.config.js

**Comment by wereHamster** [comment]
I see. We'll probably update to webpack 4 at some point. However if you'd like to upgrade to webpack 4 sooner, and are familiar with webpack config, I suggest that you create the whole webpack config yourself. There are only two changes to your project setup you need to make so that catalog works correctly:

1. Use the catalog loader for *.md files:

```
rules: [
  {
    test: /\.md$/,
    use: ["catalog/loader", "raw-loader"]
  }
]
```

2. Use the catalog babel preset, for example in your .babelrc:

```
{
  "presets": ["react", "es2015", "catalog/babel"],
  "plugins": [
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    "transform-class-properties"
  ]
}
```

**Comment by gaui** [comment]
I would recommend [Parcel](https://parceljs.org) instead of Webpack. This is a true zero configuration bundler. It's awesome!

**Comment by herrstucki** [comment]
Yes, I've been looking into Parcel but so far I haven't been happy with the performance (cold start in dev mode took ~40s) and I had an issue where code wouldn't update after edits. So for the time being, webpack seems like the safer bet.

Upgrading to webpack 4 is definitely something on our list, but it would mean a breaking change for people who relied on compatibility with webpack 3. The plan is to decouple the Catalog CLI from the Catalog itself anyway, so people can combine them freely.

Also: zero configuration just means that there's a *lot* of configuration and assumptions baked-in – which is also the case for Catalog's CLI. If we supported things like SASS and TypeScript out-of-the-box it would also be quite close to zero configuration for most cases.

**Comment by gaui** [comment]
By any chance, do you have the Webpack MD loader plugin for Parcel? 😇
