### ISSUE TITLE
Remove page styles and scripts?

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#44]
It's not clear to me why we should keep them. If someone wants to add custom CSS and scripts, they should do so in the HTML file.

What do you think @naehrstoff?

**Comment by herrstucki** [comment]
To be clear: I mean the styles and scripts which are configured via `Catalog.start()`

**Comment by naehrstoff** [comment]
We have used them in projects where it was important to add certain styles to one Catalog page only, but not the others. Also, the reason scripts are in there, is that we need to make sure that Catalog is properly loaded and ready before other scripts can be run (e.g. if they expect DOM elements to be there).

In summary:

* Not sure we need the styles, but we have used them
* We need a way to run scripts only after Catalog has rendered. If it is done this way or in a better way doesn't really matter that much, as long as it works :)

**Comment by herrstucki** [comment]
I left them in there but I think we can revisit this in the future.
