### ISSUE TITLE
 babel-core upgrade to latest version

### ISSUE THREAD

**Issue by DinakaranS** [interactivethings/catalog#459]
Hi,

I am using catalog in my project. It's awesome, can the babel-core can be upgraded to the latest version.

**Comment by the-simian** [comment]
I think this is addressed in #453 , is that correct?

**Comment by piotrf** [comment]
Seems like it, though unsure how to use that if at all possible. I can see all the new packages on `npm`, but can’t figure out what to replace `catalog start` with. 

I reckon CLI is not ready yet? I get `error Couldn't find package "@catalog/webpack-loader@^0.0.4" required by "@catalog/cli" on the "npm" registry.` when trying to install it. 

Happy to help testing the new split package infrastructure.

**Comment by piotrf** [comment]
Got it https://github.com/interactivethings/catalog/releases/tag/v4.0.1-canary.0 😅

**Comment by the-simian** [comment]
@piotrf is catalog now upgraded to the latest version of babel? Any idea how long until this gets released? appreciate the project, thank you!

**Comment by piotrf** [comment]
Not sure, but I made Catalog v4.0.1-canary.0 (linked above) work with custom webpack config as follows:

```
module.exports = {
  webpack: (catalogWebpackConfig, { paths, dev, framework }) => {
    const modifiedWebpackConfig = {
      ...catalogWebpackConfig,
      module: {
        rules: [
          { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
          {
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
          },
          {
            test: /\.md/,
            use: ['@catalog/markdown-loader', 'raw-loader']
          },
          {
            test: /\.m?js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env', '@babel/preset-react'],
                plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-proposal-export-default-from']
              }
            }
          }
        ]
      }
    };
    return modifiedWebpackConfig;
  }
};
```
