### ISSUE TITLE
Help! Where to set useBrowserHistory

### ISSUE THREAD

**Issue by nohue** [interactivethings/catalog#461]
Hi there, I am struggling with setting up **useBrowserHistory to true**, as the instructions found at [this link](https://docs.catalog.style/configuration/other) do not apply to my setup.

My project settings are all included within a **index.js** file, which lists pages within a `const pages = {...}`, theme settings within a `const theme = {...}` and then it renders the app using the following:

```
ReactDOM.render(
  <Catalog title="Catalog" pages={pages} theme={theme} />,
  document.getElementById("catalog")
);
```

Where/how in this structure should I be including the userBrowserHistory and set it to true? This is so I can try circumvent the issue with anchor links not working on Safari (bug raised separately) and ideally use html specimens to include rich content and links to specific sections of a page.

Thank you in advance for your suggestions!

**Comment by herrstucki** [comment]
In your example this would be

```js
ReactDOM.render(
  <Catalog useBrowserHistory title="Catalog" pages={pages} theme={theme} />,
  document.getElementById("catalog")
);
```

**Comment by nohue** [comment]
URLs are working great and so are anchor links. Thank you!!
