### ISSUE TITLE
Change port for Heroku Deploy

### ISSUE THREAD

**Issue by TheAleSch** [interactivethings/catalog#467]
I want to make my catalog public, but for that I need to change the port to 80 so it can work with heroku, how should I do it?

Ty

**Comment by herrstucki** [comment]
@TheAleSch Assuming you're using the `catalog` command line: once you run `catalog build` it's just a static website that you can host pretty much anywhere you like, it doesn't need a Node.js server. Although you can host static sites on Heroku as well, it's probably more complicated to set up than for example on https://www.netlify.com/

**Comment by TheAleSch** [comment]
I think that should work for me =D Going to try... Felling dumb about not thinking of that before lol

**Comment by TheAleSch** [comment]
> @TheAleSch Assuming you're using the `catalog` command line: once you run `catalog build` it's just a static website that you can host pretty much anywhere you like, it doesn't need a Node.js server. Although you can host static sites on Heroku as well, it's probably more complicated to set up than for example on https://www.netlify.com/

Well I did the build with the following command: npm run catalog-build -u --public-url=/helixp/
for this URL https://thealesch.github.io/helixp/ but I'm getting an 404 on the js.

Instead of generation the url as https://thealesch.github.io/helixp/static/manifest.88ae740c.js 
it goes https://thealesch.github.io/static/manifest.88ae740c.js

**Comment by herrstucki** [comment]
I think you need to change the command to

    npm run catalog-build -- --public-url=/helixp/

(Note the additional `--`)

**Comment by TheAleSch** [comment]
It did work! Thank you dude =D
