### ISSUE TITLE
Emotion css prop not working

### ISSUE THREAD

**Issue by nervetattoo** [interactivethings/catalog#473]
I have [a library](https://github.com/taskanalytics/genus) that uses Emotion v10 where the `css` prop is not working. Given that Catalog uses Emotion as well now I was expecting this to just work, but I guess the reason is that Catalog uses v9 and doesn't ship the [required babel preset](https://emotion.sh/docs/@emotion/babel-preset-css-prop) for it.

A, probable?, quick fix for this is to upgrade to v10 in Catalog itself and include the preset. I guess I could hack around with the `catalog.config.js` to inject the preset to the babel loader, but that seems very fragile for something that I assume will be supported by said upgrade at some point anyway.

If it sounds good I can probably go ahead with a PR for the upgrade @herrstucki

**Comment by herrstucki** [comment]
Hi!

Have you tried using the [JSX pragma](https://emotion.sh/docs/css-prop#jsx-pragma) or creating a .babelrc with the Emotion preset? I don't think Catalog's own use of Emotion should conflict with Emotion 10.

**Comment by nervetattoo** [comment]
You're right, the pragma works as expected. I had tested it previously but silly me forgot the jsx import last time 🤦‍♂️
