### ISSUE TITLE
The page header vanishes if the content is taller than the screen

### ISSUE THREAD

**Issue by grossbart** [interactivethings/catalog#487]
If there is a lot of content on a page, it will push out the page header.

![catalog-page-header](https://user-images.githubusercontent.com/10811/60863984-955d0580-a222-11e9-957a-d996ddb920e5.gif)

Version: catalog@4.0.1-canary.1

**Comment by herrstucki** [comment]
I can't reproduce this. Are you rendering Catalog _inside_ some other content?

**Comment by herrstucki** [comment]
Does this happen here for you too? https://v4--catalog-docs.netlify.com/specimens/audio

**Comment by grossbart** [comment]
Ah. I'm rendering from Next, which wraps the whole page inside a `<div id="__next">`. This has the style `height: 100%` by us, which is wrong and should be `min-height: 100%`.
