### ISSUE TITLE
Remove run-script option from Html specimen

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#67]
Somehow it feels like a really bad idea to parse script tags from HTML code and execute them.

We still have the per-page scripts option if we really need to e.g. instantiate a jQuery date picker or something like that …

**Comment by naehrstoff** [comment]
I remember: this was added for iframes, i.e. when a component is rendered not directly on a page but in an iframe (we had this option at a certain point a while back), we needed to be able to run a script within the iframe. I think this is no longer needed.
