### ISSUE TITLE
Start heading hierarchy at h1, not h2

### ISSUE THREAD

**Issue by naehrstoff** [interactivethings/catalog#71]
Now that the page title is automatically generated, it is weird that the Markdown headings still start at `<h2>`. The hierarchy should start at `<h1>` now. Also: there are no more cards, so the special status of `<h2>` is no more.

**Comment by herrstucki** [comment]
Well structurally there still are cards (do we need them?) but not visually.

**Comment by naehrstoff** [comment]
The purpose of the cards was to group related content, e.g. buttons, links, etc. Now that we don't have them anymore we might want to first see whether it works well and then get rid of the cards – if they're not there visually, there's no use in keeping them :)

**Comment by mhintz** [comment]
With an h1 in a Readme file, the style is missing. I guess this is because catalog doesn't support h1 ?

![screen shot 2015-12-03 at 15 30 45](https://cloud.githubusercontent.com/assets/2789742/11563215/0b52783a-99d3-11e5-92ef-f0ac811e2aab.png)

**Comment by herrstucki** [comment]
Yeah, we used it for the page title but that's now pulled from the Catalog configuration

**Comment by herrstucki** [comment]
h1 should just have the same style as h2

**Comment by herrstucki** [comment]
Still need to remove the <Card> components at some point …
