### ISSUE TITLE
Code specimen should not be parsed as yaml

### ISSUE THREAD

**Issue by naehrstoff** [interactivethings/catalog#72]
I wanted to use dashes in a code example like so:

```
- A
  + B
  + C
- D
```

This fails with “Warning: Failed propType: Invalid prop `body` of type `array` supplied to `Code`, expected `string`. Check the render method of `Specimen`.” Possibly because it is parsed as Yaml.

Does it really make sense to parse code specimens as Yaml? I would expect to be able to write _anything_ into a code specimen without worrying about such things – code takes many forms.

**Comment by herrstucki** [comment]
Yes, the same problem appears if you enter a valid JSON string :sweat:

Currently, the Specimen itself doesn't define how the Markdown code block is parsed, that happens one step earlier.

It would be much better if the specimen could define (or choose) that itself. The place where I would see that implemented is at the `Specimen` HOC.

Now:

```js
export default Specimen(Code);
```

I suggest something along the lines of this:

```js
export default Specimen({parseObject: false})(Code);
```

**Comment by naehrstoff** [comment]
Maybe instead of making the option binary, make it a pipeline similar to Webpack loaders?

**Comment by herrstucki** [comment]
Yep, we need more flexibility than that. There's two parts to parsing a specimen code block:

#### Options

Options are what's defined after the specimen type e.g.

```
```type|option1,option2
```

All options get parsed into booleans, except for `span-[1-6]` and `lang-{lang}`. So

```
myspecimen|foo,bar-baz,span-3
```

gets parsed into

```js
{
  foo: true,
  barBaz: true,
  span: 3
}
```

… which in turn gets passed in as props on the specimen component.

I like this very much, but the problem is that the `span` and `lang` options are now hard-coded. This makes sense for `span` because all the specimens get wrapped in a `<Span>` which uses that prop. For `lang` it should be Code specimen specific though. Therefore there needs to be a way for specimens to extend that.

#### Body

On the other hand, the body it can only be parsed as YAML/JSON. If it can't be parsed, just the string is returned. Since only arrays or objects make sense in YAML/JSON, this could be a binary option.

A nice improvement could be however to map the YAML/JSON body to props instead of just passing one `body` prop to the specimen.

If the body is an array, instead of passing that to the specimen, we'd just render multiple specimens. This would make the specimen code itself nice and clean, since we can specify all the props and not have to deal with multiple instances inside the specimen's `render()`.

So instead of rendering this

```
```myspecimen|span-3
[
  {"a": 1, "b": 2},
  {"a": 2, "b": 1}
]
```
```

into

```js
<MySpecimen span={3} body={[{a: 1, b: 2}, {a: 2, b: 1}]} />
```

we'd render this

```js
[
  <MySpecimen span={3} a={1} b={2} />,
  <MySpecimen span={2} a={2} b={1} />
]
```

(maybe wrap them in a `<Group>` for layout reasons)

#### So …

… this could lead to something like this

```js
export default Specimen({
  optionProps: [{
    test: /^lang-(\w+)$/, parse: (value) => ({lang: value})
  }],
  bodyProps: ({a, b}) => ({
    a: +a,
    b
  })
})(MySpecimen);
```

(exact API TBD)

**Comment by herrstucki** [comment]
Cf. react-redux' [`connect()` API](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)
