### ISSUE TITLE
Importing in another repo fails if raw-loader isn't installed in parallel

### ISSUE THREAD

**Issue by mhintz** [interactivethings/catalog#84]
Importing catalog (from node_modules) into another project fails if raw-loader isn't installed by the importing project

`import * as Catalog from 'catalog';`
caused the problem

the problem line:
`line 8 in components/Page/PageContentLoader: const getDocContext = () => require.context('raw!../../../docs', true, /\.md$/);`

Happened in catalyst 2 development, probably possible to reproduce.

**Comment by herrstucki** [comment]
Fixed. You need to install `raw-loader` separately though if you want to use the catalog loader.
