### ISSUE TITLE
Add emoji support

### ISSUE THREAD

**Issue by mhintz** [interactivethings/catalog#86]
:smiley:

**Comment by mhintz** [comment]
Maybe with https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone ?

**Comment by herrstucki** [comment]
Definitely a very important enhancement :grin: 

I'd rather have GH-style emoji code (like `:grin:`) parsing than unicode strings to img tag conversion like twemoji does. I guess the best way to do it is via the Markdown parser, so this is related to #37.

**Comment by bldng** [comment]
I propose we close this for now because compared to using the OS input when documenting, it adds too much weight (around 19kb for lookup during markdown parsing) 😢
