### ISSUE TITLE
Better display of color specimen labels

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#89]
The CSS-only solution is not working for dark colors. I suggest using https://github.com/d3/d3-color, and using the luminance component `l` of `hcl(color)` to compare with a threshold. Based on that, either use a dark or light color for the label.

**Comment by naehrstoff** [comment]
Is the CSS-only solution you refer to https://css-tricks.com/reverse-text-color-mix-blend-mode ? Maybe write this down in the implementation for future reference so that we can switch to it when browsers are ready …

**Comment by herrstucki** [comment]
I don't think a difference blend mode would give us the desired behavior (white text on dark colors, black text on bright ones)?

**Comment by naehrstoff** [comment]
Yes, the results might be a bit ugly :)
