### ISSUE TITLE
Go back to hosting on GH pages

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#90]
Because npmcdn is using CloudFlare, it may get blocked by [Privacy Badger](https://www.eff.org/privacybadger). The maintainer of npmcdn doesn't want to do anything about that, so I suggest we go back to hosting the built files on GH pages like we did pre-2.0.

PS: this was reported at https://github.com/mjackson/npmcdn.com/issues/2, but that's a 404 now because the issues got disabled on that repo ¯\_(ツ)_/¯

**Comment by naehrstoff** [comment]
We could also use Codeship to deploy this to our servers. npmcdn doesn't do much more than that, does it?
