### ISSUE TITLE
Can't use multiple children in HintSpecimen

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#91]
Example:

```
<HintSpecimen>
  This is a <strong>very</strong> important hint.
</HintSpecimen>
```

I see one warning and one exception in the dev console:

```
Warning: Failed propType: Invalid prop `children` of type `array`
supplied to `Hint`, expected `string`. Check the render method
of `SpecimenContainer`.
```

and

```
Uncaught TypeError: src.replace is not a function
```

Haven't tested other specimens, but I suspect they might suffer from the same problem as well.

**Comment by herrstucki** [comment]
Why don't you just provide a string then? :smile: 

```js
<HintSpecimen>
  This is a **very** important hint.
</HintSpecimen>
```

But we *could* support it in the same way as in the [Page component](https://github.com/interactivethings/catalog/blob/master/src/components/Page/Page.js#L32-L41).

**Comment by wereHamster** [comment]
Could do that. But I'm already in full JSX land so I wanted to use the JSX tags directly instead of going through markdown. Could be useful in more complex cases when you want to add icons into the hint, or use more complex layout (e.g. a grid to split the content into two columns). Just thinking out loud :)

**Comment by naehrstoff** [comment]
This doesn't just apply to the HintSpecimen, I think. I also encountered this when I tried to add several icons to one ReactSpecimen like so:

```
<ReactSpecimen>
<IconA /> <IconB />
</ReactSpecimen>
```

What I did was wrap a `<div>` around the icons and that works well. But it's a bit counter-intuitive and non-React-y.

**Comment by herrstucki** [comment]
Regarding the ReactSpecimen: I'd like to keep it as it is. Having multiple elements in the Markdown variant also doesn't work, and I think one specimen per element is how it should be anyway.
