### ISSUE TITLE
Decouple from react-router?

### ISSUE THREAD

**Issue by swissmanu** [interactivethings/catalog#93]
Are there plans to get rid of the `react-router` dependency?
I was not able to integrate with a project which uses its own routing mechanisms.

**Comment by herrstucki** [comment]
You _should_ be able to use it without react-router (although currently it needs to be installed). `configureRoutes` returns the routes as plain arrays and objects. They're structured in a way like react-router understands but there shouldn't be a reason why it doesn't work with other routers.

An expample of how it could work:

```js
import {configureRoutes} from 'catalog';

const catalogRoutes = configureRoutes({
  title: 'Foo',
  basePath: 'styleguide',
  pages: [/*...*/]
});

/* catalogRoutes:
{
  component: CatalogContext (wrapper for everything),
  childRoutes: [
    {path: '/', component: ...},
    ...
  ]
}
*/
```

Let me know if that works. I'd be happy to facilitate this use case further if it makes sense.

**Comment by herrstucki** [comment]
Ah no, we depend on react-router internally as well. So that won't work as nicely. Shouldn't be too complicated to get it there. Could you describe in more detail what you want to do with some example code? Thanks!

**Comment by swissmanu** [comment]
hi @herrstucki 
thank you for the reply. it would be awesome if i really just could render a  `<catalog />` component somewhere in my application and everything works...
@wereHamster should already have all the information about my enquiry. please let me know if i can provide any further information :)

**Comment by swissmanu** [comment]
awesome stuff. thanks for the enhancment!
