### ISSUE TITLE
Crash when code block contains what looks like valid YAML

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#95]
I have the following text in my markdown file:

````
    ```code|lang-js
    const stringAndNumber: Tuple2<string,number> = mkTuple2("string", 42);
    ```
````

The specimen body parser parses the text as a YAML block and empty/undefined children. Later React emits this warning:

```
Warning: Failed propType: Required prop `children` was not specified in `Code`.
Check the render method of `SpecimenContainer`.
```

I'll prepare a pull request once I finish writing this documentation.

**Comment by wereHamster** [comment]
Looks like this is the expected behavior. I was able to work around it by prepending `---` to the text, like this:

```
---
const stringAndNumber: Tuple2<string,number> = mkTuple2("string", 42);
```

**Comment by herrstucki** [comment]
Yes, this is unfortunate. It also happens in the React Specimen, whenever there's a `:`, e.g.

```
<div style={{fontSize: 30}}>foo</div>
```

We should try to fix that.
